version: '3'

services:
  rsshub:
    image: diygod/rsshub
    container_name: rsshub
    restart: always
    ports:
      - "1200:1200"
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: "redis://redis:6379/"
      PUPPETEER_WS_ENDPOINT: "ws://browserless:3000"
    depends_on:
      - redis
      - browserless
    networks:
      - rsshub-network

  browserless:
    image: browserless/chrome
    container_name: browserless
    restart: always
    environment:
      MAX_CONCURRENT_SESSIONS: 10
      PREBOOT_CHROME: "true"
      CONNECTION_TIMEOUT: 60000
    networks:
      - rsshub-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - rsshub-network

  rsshub-admin:
    build: .
    container_name: rsshub-admin
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - RSSHUB_BASE_URL=http://127.0.0.1:1200
      - SECRET_KEY=change-this-to-a-random-string
    volumes:
      - ./instance:/app/instance
    depends_on:
      - rsshub
    networks:
      - rsshub-network

networks:
  rsshub-network:

volumes:
  redis-data: